routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Auth::routes(['verify' => true]);

// Admin Routes
Route::get('admin', function(){
    return redirect()->route('admin.signin');
});

Route::get('/', ['as' => 'admin.signin', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::get('/verify/registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\VerificationController@verifyUser']);
Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('set_password', ['as' => 'password.set', 'uses' => 'Auth\SetPasswordController@set_password']);
Route::get('user/change-password', ['as' => 'change_password', 'uses' => 'Auth\ChangePasswordController@showChangePasswordForm']);
Route::post('user/change-password', ['as' => 'auth.change_password', 'uses' => 'Auth\ChangePasswordController@changePassword']);



Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::group([
        'middleware' => ['auth', 'role:developer|admin|super-admin'],
    ], function () {


        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');
        Route::resource('users','UserController');

    });
});


Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'as' => 'member.'
], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::group([
        'middleware' => ['auth', 'role:master-member|developer|admin|super-admin'],
    ], function () {

        Route::resource('settings','SettingController');
        Route::get('company-fiscal-year', ['as' => 'settings.company_fiscal_year', 'uses' => 'SettingController@company_fiscal_year']);
        Route::post('set-company-fiscal-year', ['as' => 'settings.set_company_fiscal_year', 'uses' => 'SettingController@set_company_fiscal_year']);
        Route::get('general-settings', ['as' => 'settings.general_settings', 'uses' => 'SettingController@general_settings']);
        Route::post('set-print-page-setup', ['as' => 'settings.set_print_page_setup', 'uses' => 'SettingController@set_print_page_setup']);
        Route::resource('users','UserController');
        Route::get('set-users-company', ['as' => 'users.set_users_company', 'uses' => 'UserController@set_users_company']);
        Route::post('set-users-company', ['as' => 'users.save_users_company', 'uses' => 'UserController@save_users_company']);
        Route::post('set-cash-setup', ['as' => 'settings.set_cash_setup', 'uses' => 'SettingController@set_cash_setup']);

    });

    Route::group([
        'middleware' => ['auth'],
    ], function () {

      
    });

});

resources/views/layouts/back-end/partials/breadcrumb.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 2:39 PM
 */
?>

<!-- Content Header (Page header) -->
<section class="content-header">

    <!-- BEGIN PAGE BAR -->

    @isset($breadcrumb)

        @if( isset($data['heading']) )
            <h1 class="page-title">
                {{ $data['heading'] ? $data['heading'] : $data['name']}}
            </h1>
        @endif

    <ol class="breadcrumb">
        @foreach($breadcrumb as $b)
            <li class="{{ $loop->last ? 'active' : '' }}">
                @if(isset($b['href']))
                    <a href="{{$b['href']}}">
                        <i class="{{ isset($b['icon']) ? $b['icon'] : '' }}"></i>
                        {{$b['name']}}
                    </a>
                @else
                    <strong>{{$b['name']}}</strong>
                @endif
            </li>
        @endforeach
    </ol>
</section>




@endisset
<!-- END PAGE TITLE-->

resources/views/layouts/back-end/partials/footer.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 11:39 AM
 */

?>

<!-- /.content-wrapper -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <span><strong>Copyright &copy; 2019 <a href="#">{{  human_words(config('app.name')) }}</a>. </strong> All rights reserved.</span>
    &nbsp &nbsp &nbsp &nbsp &nbsp<span> Developed By <strong><a href="#">R-Creation </a></strong></span>
</footer>

resources/views/layouts/back-end/partials/left-sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 11:40 AM
 */
?>

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('public/adminLTE/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p class="username">{{ Auth::user()->full_name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        {{--<form action="#" method="get" class="sidebar-form">--}}
            {{--<div class="input-group">--}}
                {{--<input type="text" name="q" class="form-control" placeholder="Search...">--}}
                {{--<span class="input-group-btn">--}}
                    {{--<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>--}}
                    {{--</button>--}}
                {{--</span>--}}
            {{--</div>--}}
        {{--</form>--}}
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header text-uppercase">Profile Setting</li>
            <li>
                <a href="{{ route('change_password') }}">
                    <i class="fa fa-key"></i>
                    <span>Change Password</span> </a>
            </li>
            <li class="header">MAIN NAVIGATION</li>
            <li>
                @php
                    $route = Auth::user()->hasRole(['admin','super-admin','developer']) ? 'admin' : 'member';
                    $route .= '.dashboard';
                @endphp
                <a href="{{ route($route) }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>

            
            <li class="header">Admin Settings</li>

            {{-- @if(Auth::user()->can(['super-admin', 'admin'])) --}}
                <li class="treeview">
                <a href="#">
                    <i class="fa fa-gears"></i> <span>Settings</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('member.settings.general_settings') }}"><i class="fa fa-cog"></i> General Settings</a></li>
               </ul>
            </li>
           

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Users</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('member.users.index') }}"><i class="fa fa-user"></i> Users</a></li>
                    <li><a href="{{ route('member.users.create') }}"><i class="fa fa-user-plus"></i> Add User</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-unlock-alt"></i> <span>Roles</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('admin.roles.index') }}"><i class="fa fa-unlock-alt"></i> Roles</a></li>
                    <li><a href="{{ route('admin.roles.create') }}"><i class="fa fa-plus"></i> Add Role</a></li>
                </ul>
            </li>

               

            {{-- @endif --}}
            @if(Auth::user()->hasRole(['super-admin']))
             
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-expeditedssl"></i> <span>Permissions</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ route('admin.permissions.index') }}"><i class="fa fa-unlock-alt"></i> Permissions</a></li>
                        <li><a href="{{ route('admin.permissions.create') }}"><i class="fa fa-plus"></i> Add Permission</a></li>
                    </ul>
                </li>

                
            @endif
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

resources/views/layouts/back-end/partials/right-sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 11:41 AM
 */
?>
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

resources/views/layouts/back-end/partials/scripts.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 11:40 AM
 */
?>

    <!-- jQuery 3 -->
<script src="{{ asset('public/adminLTE/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('public/adminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
<!-- DataTables -->
<script src="{{ asset('public/adminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>


<!-- daterangepicker -->
<script src="{{ asset('public/adminLTE/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('public/adminLTE/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('public/adminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('public/adminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>


<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<!-- SlimScroll -->
<script src="{{ asset('public/adminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('public/adminLTE/bower_components/fastclick/lib/fastclick.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>


<!-- public/adminLTE App -->
<script src="{{ asset('public/adminLTE/dist/js/adminlte.min.js') }}"></script>


<!-- public/adminLTE for demo purposes -->
<script src="{{ asset('public/adminLTE/dist/js/demo.js') }}"></script>
<script src="{{ asset('public/adminLTE/jquery.printPage.js') }}"></script>


@stack('scripts')


<script>
    mouseWheelOff();

    $('input[type=number]').attr('min', 0);

    function mouseWheelOff(){
        $('input[type=number]').on('mousewheel', function(e) {
            $(e.target).blur();
        });

        $('.input-number').keypress(function (evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode;
            if (charCode > 31 && ( charCode != 46 && (charCode < 48 || charCode > 57)))
                return false;
            return true;
        });
    }

    function company(){
        var html = '';
        @if(isset( Auth::user()->company))

        var logo = "{{  emptyCheck(Auth::user()->company->company_logo_path)}}";
        var company = "{{ emptyCheck(Auth::user()->company->company_name) }}";
        var address = "{{ emptyCheck(str_replace( array( "\n", "\r" ), array( "\\n", "\\r" ), Auth::user()->company->address)) }}";
        var city = "{{ emptyCheck(Auth::user()->company->city) }}";
        var country = "{{ emptyCheck(Auth::user()->company->country->countryName) }}";
        var phone = "{{ emptyCheck(Auth::user()->company->country->phone) }}";
        var email = "{{ emptyCheck(Auth::user()->company->country->email) }}";

         html = "<div> <div style='text-align: right !important; float: left; width:25%' >" +
            "<img width='130px !important' src='"+logo+"' alt='"+company+"'/> </div> <div  style='text-align: center !important; float: left; padding-left: 13%; width:50%' >" +
            "<h3>"+company+"</h3>" +
            "<p>"+address+" <br/> "+city+", "+country+"</p>" +
            "<p>"+phone+"</p>" +
            "<p>"+email+"</p>" +
            "</div></div>";
        @endif

        return html;
    }

        $('#print').click( function () {
            var header = company();
            var printContents = $('#custom-print').html();
            var originalContents = $('body').html();

            $('body').html(header+printContents);
            window.print();
            $('body').html(originalContents);
        });


    var $body = $('body');

    $body.on('click', '.delete-confirm', function () {
        var $this = $(this);
        bootbox.confirm("Are you sure? " ,  function(result) {

            if (result){
                $.ajax({
                    url: $this.data('target'),
                    type: "DELETE",
                    dataType: "json",
                    success: function (data) {
                        bootbox.alert("Delete successfully completed",
                            function () {
                                location.reload();
                            });
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        var response = xhr.responseJSON;
                        bootbox.alert("OOP! Sorry Response Denied");
                    }
                });
                }else{
                        bootbox.alert("OOP! Sorry Response Denied");
                }
        });
    });

    $body.on('click', '.process-confirm', function () {
        var $this = $(this);
        bootbox.confirm("Are you sure? It will take more time to process complete" ,  function(result) {

            if (result){
                bootbox.alert("Processing Start ..............");
            }else{
                bootbox.alert("OOP! Sorry Response Denied");
            }
        });
    });


    $('#btn-print, .btn-print').printPage();

    $('.content').click( function (e) {
        // $(".dt-button-collection").css('display','none');
    })

    </script>

resources/views/layouts/back-end/partials/styles.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 2/26/2019
 * Time: 11:41 AM
 */
?>

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/font-awesome/css/font-awesome.min.css')}}">
{{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/fontawesome.min.css">--}}
{{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">--}}
{{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/solid.min.css">--}}
{{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/brands.min.css">--}}
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/Ionicons/css/ionicons.min.css')}}">
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

<!-- Date Picker -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">

@stack('styles')

<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/AdminLTE.min.css')}}">
<link rel="stylesheet" href="{{ asset('public/adminLTE/custom.css')}}">
<link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/top-menu.css')}}">
<!-- public/adminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{ asset('public/adminLTE/dist/css/skins/_all-skins.min.css')}}">



<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

<style type="text/css">

    .username{
        text-transform: capitalize;
    }

    div.dt-button-background{
        position: relative !important;
    }
</style>