routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Auth::routes(['verify' => true]);

// Admin Routes
Route::get('admin', function(){
    return redirect()->route('admin.signin');
});

Route::get('/', ['as' => 'admin.signin', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::get('/verify/registration/{id}', ['as' => 'verify.registration', 'uses' => 'Auth\VerificationController@verifyUser']);
Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('set_password', ['as' => 'password.set', 'uses' => 'Auth\SetPasswordController@set_password']);
Route::get('user/change-password', ['as' => 'change_password', 'uses' => 'Auth\ChangePasswordController@showChangePasswordForm']);
Route::post('user/change-password', ['as' => 'auth.change_password', 'uses' => 'Auth\ChangePasswordController@changePassword']);



Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'as' => 'admin.'
], function () {

    Route::group([
        'middleware' => ['auth', 'role:developer|admin|super-admin'],
    ], function () {


        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::resource('roles','RoleController');
        Route::resource('permissions','PermissionController');
        Route::resource('users','UserController');

    });
});


Route::group([
    'prefix' => 'member',
    'namespace' => 'Member',
    'as' => 'member.'
], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

    Route::group([
        'middleware' => ['auth', 'role:master-member|developer|admin|super-admin'],
    ], function () {

        Route::resource('settings','SettingController');
        Route::get('company-fiscal-year', ['as' => 'settings.company_fiscal_year', 'uses' => 'SettingController@company_fiscal_year']);
        Route::post('set-company-fiscal-year', ['as' => 'settings.set_company_fiscal_year', 'uses' => 'SettingController@set_company_fiscal_year']);
        Route::get('general-settings', ['as' => 'settings.general_settings', 'uses' => 'SettingController@general_settings']);
        Route::post('set-print-page-setup', ['as' => 'settings.set_print_page_setup', 'uses' => 'SettingController@set_print_page_setup']);
        Route::resource('users','UserController');
        Route::get('set-users-company', ['as' => 'users.set_users_company', 'uses' => 'UserController@set_users_company']);
        Route::post('set-users-company', ['as' => 'users.save_users_company', 'uses' => 'UserController@save_users_company']);
        Route::post('set-cash-setup', ['as' => 'settings.set_cash_setup', 'uses' => 'SettingController@set_cash_setup']);

    });

    Route::group([
        'middleware' => ['auth'],
    ], function () {

      
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait { restore as private restoreA; }
    use SoftDeletes { restore as private restoreB; }

    public function restore()
    {
        $this->restoreA();
        $this->restoreB();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'full_name', 'email',  'verify_token', 'status',
    ];

    protected $guarded = [ 'phone', 'password' ];

    protected $dates = ['deleted_at'];

    protected static $logAttributes = ['*'];
    protected static $recordEvents = [ 'updated', 'deleted'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token', 'verify_token'
    ];

    protected $appends = ['user_details', 'uc_full_name'];


    /**
     * Scope a query to only include active models
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('status', 'active');
    }

    public function getUserDetailsAttribute()
    {
        return $this->full_name." (".$this->email." ".$this->phone.") ";
    }

    public function getUcFullNameAttribute()
    {
        return ucfirst($this->full_name);
    }

    public function scopeSystemUser($query)
    {
        return $query->whereNotIn('full_name', ['superadmin','developer','master-member']);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Company;
use App\Models\Membership;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function create()
    {
        $data['memberships'] = Membership::where('status', 'active')->pluck('display_text','id');

        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $modal = User::findOrFail($id);
        $modal->delete();

        return response()->json([
            'data' => [
                'message' => 'Successfully deleted'
            ]
        ], 200);
    }

}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
     public function index(){
        return view('member.dashboard.index');
    }
}

app/Http/Controllers/Member/SettingController.php
<?php

namespace App\Http\Controllers\Member;

use App\Models\CashOrBankAccount;
use App\Models\Company;
use App\Models\FiscalYear;
use App\Models\Member;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SettingController extends Controller
{

    public function company_fiscal_year()
    {
        $data = [];
        $data['companies'] = Company::active()->authMember()->get()->pluck('company_name', 'id');
        $data['company_fiscal_years'] = Company::active()->authMember()->paginate(10);
        $data['fiscal_year'] = FiscalYear::active()->authMember()->get()->pluck('fiscal_year_details', 'id');
        return view('member.settings.company_fiscal_year', $data);
    }

    public function set_company_fiscal_year(Request $request)
    {
        $rules = [
            'company_id' => 'required',
            'fiscal_year_id' => 'required'
        ];

        $this->validate($request, $rules);

        $company  = Company::authMember()->where('id', $request->company_id)->first();
        $company->fiscal_year_id = $request->fiscal_year_id;
        $company->save();
        $status = ['type' => 'success', 'message' => 'Successfully Fiscal Year Add Company '.$company->company_name];
        return back()->with('status', $status);
    }

    public function general_settings()
    {
        $settings = Setting::where('key', '=', 'print_page_setup')->first();
        $memberCode = Auth::user()->member->member_code;
        $members = Member::where('member_code', '=', $memberCode)->first();
        $cashs = CashOrBankAccount::withoutSupplierCustomer()->pluck('title', 'account_type_id');


        $data = [];
        $data['print_page_option'] = [
            'pos' => "POS Print",
            'default' => "Default A4 Print"
        ];
        $data['memberInfo'] = $members;
        $data['cashs'] = $cashs;

        return view('member.settings.general_settings', $data);
    }

    public function set_print_page_setup(Request $request)
    {
        $settings = Setting::where('key', '=', 'print_page_setup')->first();

        $input = [];
        if( isset($request->print_page_setup) && !$settings)
        {
            $input['key'] = 'print_page_setup';
            $input['value'] = $request->print_page_setup;
            Setting::create($input);
        }else{
            $input['value'] = $request->print_page_setup;
            $settings->update($input);
        }

        $status = ['type' => 'success', 'message' => 'Successfully Print Page setup Done'];
        return back()->with('status', $status);
    }


    public function set_cash_setup(Request $request)
    {
        $settings = Setting::where('key', '=', 'cash_account_id')->first();
        $Cash_settings = Setting::where('key', '=', 'cash_bank_id')->first();

        $cashs = CashOrBankAccount::where('account_type_id', $request->cash_account_id)->first();

        $input = [];
        if( isset($request->cash_account_id) && !$settings)
        {
            $input['key'] = 'cash_account_id';
            $input['value'] = $request->cash_account_id;
            Setting::create($input);

            $input = [];
            $input['key'] = 'cash_bank_id';
            $input['value'] = $cashs->id;
            Setting::create($input);
        }else{
            $input['value'] = $request->cash_account_id;
            $settings->update($input);

            $input = [];
            $input['value'] = $cashs->id;
            $Cash_settings->update($input);
        }

        $status = ['type' => 'success', 'message' => 'Successfully Cash setup Done'];
        return back()->with('status', $status);
    }


}

app/Http/Controllers/Member/UserController.php
<?php

namespace App\Http\Controllers\Member;

use App\DataTables\MemberUsersDataTable;
use App\Http\Traits\VerifyUserTrait;
use App\Models\Company;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    use VerifyUserTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(MemberUsersDataTable $dataTable)
    {
        return $dataTable->render('member.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['roles'] = Role::filter()->get()->pluck('display_name', 'id');
        return view('member.users.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->getValidationRules());

        $inputs = $request->all();
        $email = $request->email;
        $roles = $request->roles;
        $inputs['member_id'] = Auth::user()->member_id;
        $inputs['membership_id'] = Auth::user()->membership_id;
        $inputs['company_id'] = Auth::user()->company_id;
        $inputs['verify_token'] = $verify_token = verify_token_generate();
        $inputs['status'] = "inactive";

        DB::beginTransaction();

        try{
            $saveUser = User::create($inputs);

            $assignRole = $saveUser->attachRoles($roles);
            $this->sendVerifyToken($verify_token, $email, 'User');
            $status = ['type' => 'success', 'message' => "User Added Successfully ----- Say to confirm verification and set password -----"];

        }catch (\Exception $e){

            $status = ['type' => 'danger', 'message' => 'Unable to User Add'];
            DB::rollBack();
        }

        DB::commit();

        return back()->with('status', $status);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['model'] = $user = User::where('id', $id)->membersUser()->first();
        if(!$user)
        {
            $status = ['type' => 'danger', 'message' => 'User Not find'];
            return back()->with('status', $status);
        }

        $data['roles'] = Role::filter()->get()->pluck('display_name', 'id');
        $data['assignRole'] = $user->roles->toArray();
        return view('member.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user =  User::where('id', $id)->membersUser()->first();

        if(!$user)
        {
            $status = ['type' => 'danger', 'message' => 'User Not find'];
            return back()->with('status', $status);
        }

        $this->validate($request, $this->getValidationRules($id));

        $user->email = $email = $request->email;
        $user->full_name = $request->full_name;
        $user->phone = $request->phone;
        $user->status = $request->status;
        $roles = $request->roles;

        DB::beginTransaction();

        try{

            $user->save();
            $assignRole = $user->roles()->sync($roles);
            $status = ['type' => 'success', 'message' => 'User Updated Successfully'];

        }catch (\Exception $e){

            $status = ['type' => 'danger', 'message' => 'Unable to User update'];
            DB::rollBack();
        }

        DB::commit();

        return back()->with('status', $status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $modal = User::findOrFail($id);
        $modal->delete();

        return response()->json([
            'data' => [
                'message' => 'Successfully deleted'
            ]
        ], 200);
    }

    private function getValidationRules($id='')
    {
        $rules = [
            'full_name' => 'required',
        ];

        if (is_null($id)) {
            $rules['email'] = 'required|email|unique:users';
            $rules['phone'] = 'nullable|unique:users,phone';
        } else {
            $rules['email'] = 'required|email|unique:users,email,' . $id;
            $rules['phone'] = 'nullable|unique:users,phone,' . $id;
        }

        return $rules;
    }


    public function set_users_company()
    {
        $data = [];
        $data['companies'] = Company::active()->authMember()->get()->pluck('company_name', 'id');
        $data['users'] = User::active()->membersUser()->get()->pluck('user_details', 'id');
        $data['users_company'] = User::active()->membersUser()->systemUser()->paginate(10);
        return view('member.users.company_assign', $data);
    }

    public function save_users_company(Request $request)
    {
        $rules = [
            'company_id' => 'required',
            'user_id' => 'required'
        ];

        $this->validate($request, $rules);

        $user  = User::membersUser()->where('id', $request->user_id)->first();
        $user->company_id = $request->company_id;
        $user->save();
        $status = ['type' => 'success', 'message' => 'Successfully User Add Company '.$user->full_name." ".$user->email];
        return back()->with('status', $status);
    }
}

resources/views/member/users/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 4:25 PM
 */

?>

@include('common._error')

<div class="col-md-7">
    <div class="form-group">
        <label for="full_name">Full Name <span class="text-red"> * </span> </label>
        {!! Form::text('full_name',null,['id'=>'full_name','class'=>'form-control','placeholder'=>'Enter Full Name', 'required']); !!}
    </div>
    <div class="form-group">
        <label for="email">Email <span class="text-red"> * </span> </label>
        {!! Form::text('email',null,['id'=>'email','class'=>'form-control','placeholder'=>'Enter Email', 'required']); !!}
    </div>
    <div class="form-group">
        <label for="phone">Phone  </label>
        {!! Form::text('phone',null,['id'=>'phone','class'=>'form-control input-number','placeholder'=>'Enter phone']); !!}
    </div>

</div>
<div class="col-md-12">
    <div class="form-group ">
        <label for="role">{{ isset($assignRole)?'Assigned ':'' }} Roles  </label><br/>

        @foreach( $roles as $key => $role)
            <div class="col-md-3">
                @if(isset($assignRole))
                    {!! Form::checkbox('roles[]', $key, null, ['checked' => in_array($key, $assignRole )] ) !!} {{ $role }}
                @else
                    {!! Form::checkbox('roles[]', $key, null ) !!} {{ $role }}
                @endif
            </div>
        @endforeach
    </div><br/>
</div>

resources/views/member/users/company_assign.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 3/20/2019
 * Time: 4:15 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('member.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Company  Setting',
        'href' => route('member.users.set_users_company'),
    ],
    [
        'name' => 'Set Users Company',
    ],
];

$data['data'] = [
    'name' => 'Set Users Company Setting',
    'title'=>'Set Users Company ',
    'heading' => 'Set Users Company',
];

?>
@extends('layouts.back-end.master', $data)

@push('styles')

    <link rel="stylesheet" href="{{ asset('public/adminLTE/bower_components/select2/dist/css/select2.min.css')}}">

@endpush

@section('contents')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">

        @include('common._alert')
        @include('common._error')

        <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Set Users Company </h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                {!! Form::open(['route' => 'member.users.save_users_company', 'method' => 'POST', 'role'=>'form' ]) !!}

                <div class="box-body">
                    <div class="col-md-6">

                        <div class="form-group">
                            <label for="user_id">User </label>
                            {!! Form::select('user_id',$users,null,['id'=>'user_id','class'=>'form-control select2','placeholder'=>'Select User']); !!}
                        </div>
                        <div class="form-group">
                            <label for="company_id">Company </label>
                            {!! Form::select('company_id',$companies,null,['id'=>'company_id','class'=>'form-control select2','placeholder'=>'Select Company']); !!}
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success form-group"> Save </button>
                    </div>
                </div>
                <!-- /.box-body -->

            {!! Form::close() !!}


            <!-- /.box -->
            </div>

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"> Users Assigned Company </h3>
                </div>

                <div class="box-body">
                    <div class="col-md-12">
                        <table class="table table-striped table-responsive">
                            <thead>
                            <tr>
                                <th>#SL</th>
                                <th>User Name</th>
                                <th>Assign Company</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($users_company as $key=>$value)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $value->user_details }}</td>
                                    <td>{{ $value->company ? $value->company->company_name : '' }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tr>
                                <td class="text-right">{{ $users_company->links() }}</td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')

    <script src="{{ asset('public/adminLTE/bower_components/select2/dist/js/select2.full.min.js') }}"></script>

    <script type="text/javascript">

        $(function () {
            $('.select2').select2()
        });

    </script>

@endpush

resources/views/member/users/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 12:52 PM
 */

$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('member.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Users',
        'href' => route('member.users.index'),
    ],
    [
        'name' => 'Create',
    ],
];

$data['data'] = [
    'name' => 'Users',
    'title'=>'Create User',
    'heading' => 'Create User',
];

?>
@extends('layouts.back-end.master', $data)

@section('contents')
<div class="row">
    <!-- left column -->
    <div class="col-md-12">

        @include('common._alert')
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create User</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->

            {!! Form::open(['route' => 'member.users.store', 'method' => 'POST', 'role'=>'form' ]) !!}

                <div class="box-body">

                    @include('member.users._form')

                    <div class="box-footer">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->

            {!! Form::close() !!}
        <!-- /.box -->
    </div>
    </div>
</div>
@endsection


@push('scripts')

    <!-- CK Createor -->
    <script src="{{ asset('public/adminLTE/bower_components/ckeditor/ckeditor.js') }}"></script>

    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKCreateor
            // instance, using default configuration.
            CKEDITOR.replace('description');
        })
    </script>
@endpush

resources/views/member/users/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: R-Creation
 * Date: 2/27/2019
 * Time: 12:52 PM
 */
$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('member.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Users',
        'href' => route('member.users.index'),
    ],
    [
        'name' => 'Edit',
    ],
];

$data['data'] = [
    'name' => 'Users',
    'title'=>'Edit User',
    'heading' => 'Edit User',
];

?>
@extends('layouts.back-end.master', $data)

@section('contents')
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">

            @include('common._alert')

            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Update </h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->

                {!! Form::model($model, ['route' => ['member.users.update', $model],  'method' => 'put']) !!}

                <div class="box-body">

                    @include('member.users._form')

                    <div class="box-footer">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->

            {!! Form::close() !!}
            <!-- /.box -->
            </div>
        </div>
    </div>
@endsection


@push('scripts')

    <!-- CK Editor -->
    <script src="{{ asset('public/memberLTE/bower_components/ckeditor/ckeditor.js') }}"></script>

    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('description');
        })
    </script>
@endpush

resources/views/member/users/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Mobarok Hossen
 * Date: 1/1/2018
 * Time: 11:37 PM
 */


$data['breadcrumb'] = [
    [
        'name' => 'Home',
        'href' => route('admin.dashboard'),
        'icon' => 'fa fa-home',
    ],
    [
        'name' => 'Users',
        'href' => route('admin.users.index'),
    ],
    [
        'name' => 'Index',
    ],
];

$data['data'] = [
    'name' => 'Users',
    'title'=>'List Of Users',
    'heading' => 'List Of Users',
];

?>

@extends('layouts.back-end.master', $data)

@section('contents')


    <div class="row">
        <div class="col-xs-12">

            @include('common._alert')

            <div class="box">
                <div class="portlet light">

                    <div class="box-header">
                        <a href="{{ route('member.users.create') }}" class="btn btn-info"> <i class="fa fa-plus"> Add User </i></a>
                    </div>
                    <!-- END SAMPLE FORM PORTLET-->
                </div>
                <div class="box-body">
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <!-- BEGIN SAMPLE FORM PORTLET-->

                        <div class="table-responsive">
                            {!! $dataTable->table() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
    <script src="{{ asset('public/vendor/datatables/buttons.server-side.js') }}"></script>
    {!! $dataTable->scripts() !!}
@endpush